//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    public partial class Admin_ViewAttendance
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Button btnBackTools;

        protected global::System.Web.UI.WebControls.Label lblInfo;

        protected global::System.Web.UI.WebControls.GridView gvAttendance;
    }
}
